export const studentActionTypes = {
  FETCH_STUDENT_USER_START: 'FETCH_STUDENT_USER_START',
  FETCH_STUDENT_USER_SUCCESS: 'FETCH_STUDENT_USER_SUCCESS',
  FETCH_STUDENT_USER_FAILURE: 'FETCH_STUDENT_USER_FAILURE',
  VERIFY_STUDENT_USER_START: 'VERIFY_STUDENT_USER_START',
  VERIFY_STUDENT_USER_SUCCESS: 'VERIFY_STUDENT_USER_SUCCESS',
  VERIFY_STUDENT_USER_FAILURE: 'VERIFY_STUDENT_USER_FAILURE',
}
