export const accountingActionTypes = {
  ADD_PAYMENT_DETAILS_START: 'ADD_PAYMENT_DETAILS_START',
  ADD_PAYMENT_DETAILS_SUCCESS: 'ADD_PAYMENT_DETAILS_SUCCESS',
  ADD_PAYMENT_DETAILS_FAILURE: 'ADD_PAYMENT_DETAILS_FAILURE',
  FETCH_PAYMENT_DETAILS_START: 'FETCH_PAYMENT_DETAILS_START',
  FETCH_PAYMENT_DETAILS_SUCCESS: 'FETCH_PAYMENT_DETAILS_SUCCESS',
  FETCH_PAYMENT_DETAILS_FAILURE: 'FETCH_PAYMENT_DETAILS_FAILURE',
}
